# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 08:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20160506_0541'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adult',
            managers=[
                ('men', django.db.models.manager.Manager()),
            ],
        ),
    ]
